language: python
sudo: false
cache:
  directories:
  - eggs
  - downloads
addons:
  # XXX: use an older Firefox ESR as we are stuck with selenium = 2.53.5
  #      https://github.com/SeleniumHQ/selenium/issues/2739#issuecomment-249482533
  firefox: 45.9.0esr
python:
  - 2.7
matrix:
  fast_finish: true
install:
  - virtualenv -p `which python` .
  - bin/pip install -r requirements.txt
  - bin/buildout -N buildout:download-cache=downloads code-analysis:return-status-codes=True annotate
  - bin/buildout -N buildout:download-cache=downloads code-analysis:return-status-codes=True
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- firefox -v
script:
  - bin/code-analysis
  - bin/test
after_success:
  - bin/createcoverage
  - pip install coveralls
  - coveralls
notifications:
  email:
    - itconsense@gmail.com
